// examples/vue/src/TreeNode.vue
<script setup lang="ts">
import { Draggable } from '@anil-labs/dnd'

export interface TreeItem {
  id: number
  label: string
  children: TreeItem[]
}

defineProps<{ items: TreeItem[] }>()
const emit = defineEmits<{ 'update:items': [TreeItem[]] }>()
</script>

<template>
  <Draggable
    :model-value="items"
    item-key="id"
    group="tree"
    :animation="200"
    :empty-insert-threshold="14"
    tag="ul"
    item-tag="li"
    :class="['tree-list', { 'tree-list--empty': items.length === 0 }]"
    @update:model-value="(v) => emit('update:items', v as TreeItem[])"
  >
    <template #item="{ element }">
      <div class="tree-node">
        <div class="tree-row">
          <span class="grip">⠿</span>
          <span class="tree-label">{{ element.label }}</span>
        </div>
        <TreeNode
          v-if="element.label.endsWith('/')"
          :items="element.children"
          @update:items="(v) => (element.children = v)"
        />
      </div>
    </template>
  </Draggable>
</template>

// examples/svelte/src/TreeNode.svelte
<script lang="ts">
  import { draggable } from '@anil-labs/dnd-svelte'
  import TreeNode from './TreeNode.svelte'

  export interface TreeItem {
    id: number
    label: string
    children: TreeItem[]
  }

  let {
    items,
    onItemsChange,
  }: {
    items: TreeItem[]
    onItemsChange: (items: TreeItem[]) => void
  } = $props()
</script>

<ul
  class="tree-list"
  class:tree-list--empty={items.length === 0}
  use:draggable={{
    items,
    onItemsChange,
    group: 'tree',
    animation: 200,
    emptyInsertThreshold: 14,
  }}
>
  {#each items as item, i (item.id)}
    <li data-dnd-index={i} class="dnd-item">
      <div class="tree-node">
        <div class="tree-row">
          <span class="grip">⠿</span>
          <span class="tree-label">{item.label}</span>
        </div>
        {#if item.label.endsWith('/')}
          <TreeNode items={item.children} onItemsChange={(v) => (item.children = v)} />
        {/if}
      </div>
    </li>
  {/each}
</ul>
